# Generated by Django 5.1.4 on 2024-12-17 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('site_administrator', 'Site Administrator'), ('super_administrator', 'Super Administrator')], default='student', max_length=20),
        ),
    ]
