# Generated by Django 5.1.4 on 2024-12-21 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rename_student_telegramuserandadminchat_telegram_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuserandadminmessage',
            name='sender',
        ),
        migrations.AddField(
            model_name='telegramuserandadminmessage',
            name='admin_sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='telegramuserandadminmessage',
            name='user_sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_sent_messages', to='chat.telegramuser'),
        ),
    ]
