# Generated by Django 5.1.4 on 2024-12-21 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_telegramuserandadminmessage_sender_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentandteacherchat',
            options={'verbose_name': 'Student And Teacher Chat', 'verbose_name_plural': 'Student And Teacher Chats'},
        ),
        migrations.AlterModelOptions(
            name='studentandteachermessage',
            options={'ordering': ['timestamp'], 'verbose_name': 'Student And eacher Message', 'verbose_name_plural': 'Student And Teachers Messages'},
        ),
        migrations.AlterModelOptions(
            name='systemaction',
            options={'verbose_name': 'System Action', 'verbose_name_plural': 'System Actions'},
        ),
        migrations.AlterModelOptions(
            name='telegramuserandadminchat',
            options={'verbose_name': 'Telegram User And Teacher Chat', 'verbose_name_plural': 'Telegram User AndTeacher Chats'},
        ),
        migrations.AlterModelOptions(
            name='telegramuserandadminmessage',
            options={'ordering': ['timestamp'], 'verbose_name': 'Telegram User And Admin Message', 'verbose_name_plural': 'Telegram User And Admin Messages'},
        ),
    ]
