# Generated by Django 5.1.4 on 2024-12-18 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_customuser_options_telegramuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_list', models.ManyToManyField(blank=True, limit_choices_to={'role__in': ['site_administrator', 'super_administrator']}, related_name='admin_chats', to=settings.AUTH_USER_MODEL)),
                ('student_id', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='student_chats', to=settings.AUTH_USER_MODEL)),
                ('teacher_id', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='teacher_chats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat',
                'verbose_name_plural': 'Chats',
            },
        ),
    ]
