# Generated by Django 5.1.4 on 2024-12-18 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chats',
            name='admin_list',
        ),
        migrations.AddField(
            model_name='chats',
            name='admin_list',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
