# Generated by Django 5.1.4 on 2024-12-21 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_studentandteacherchat_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuserandadminchat',
            name='messages',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.DeleteModel(
            name='TelegramUserAndAdminMessage',
        ),
    ]
