# Generated by Django 5.1.4 on 2024-12-21 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_telegramuserandadminchat_messages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuserandadminchat',
            name='admin_list',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='telegramuserandadminchat',
            name='messages',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
