# Generated by Django 5.1.4 on 2024-12-18 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_remove_telegramuser_service_id_customuser_telegram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chats',
            name='student_id',
            field=models.OneToOneField(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='student_chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chats',
            name='teacher_id',
            field=models.OneToOneField(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='teacher_chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telegram',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='chat.telegramuser'),
        ),
    ]
