# Generated by Django 5.1.4 on 2024-12-23 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_telegramuserandadminchat_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentandteacherchat',
            name='messages',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='studentandteacherchat',
            name='student',
            field=models.OneToOneField(limit_choices_to={'role': 'student'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_teacher_chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentandteacherchat',
            name='teacher',
            field=models.OneToOneField(limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_student_chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='StudentAndTeacherMessage',
        ),
    ]
