# Generated by Django 5.1.4 on 2024-12-19 11:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_chats_student_id_alter_chats_teacher_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='student_list',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'student'}, related_name='teachers', to=settings.AUTH_USER_MODEL),
        ),
    ]
