# Generated by Django 5.1.4 on 2024-12-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_customuser_student_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='student_list',
        ),
        migrations.AddField(
            model_name='customuser',
            name='student_list',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
