# Generated by Django 5.1.4 on 2024-12-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_remove_customuser_student_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='student_list',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
