# Generated by Django 5.1.4 on 2024-12-19 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_rename_chats_chat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='teacher_id',
            new_name='teacher',
        ),
    ]
