# Generated by Django 5.1.4 on 2024-12-19 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_rename_chat_studentandteacherchat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentandteacherchat',
            options={'verbose_name': 'StudentAndTeacherChat', 'verbose_name_plural': 'StudentAndTeacherChats'},
        ),
    ]
