# Generated by Django 5.1.4 on 2024-12-20 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_alter_studentandteacherchat_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=962)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('telegram', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='chat.telegramuser')),
            ],
            options={
                'verbose_name': 'SystemAction',
                'verbose_name_plural': 'SystemActions',
            },
        ),
    ]
