# Generated by Django 5.1.4 on 2024-12-20 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_systemaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemaction',
            name='action',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
