# Generated by Django 5.1.4 on 2024-12-20 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0016_alter_systemaction_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentandteacherchat',
            name='student',
            field=models.OneToOneField(limit_choices_to={'role': 'student'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentandteacherchat',
            name='teacher',
            field=models.OneToOneField(limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_chats', to=settings.AUTH_USER_MODEL),
        ),
    ]
