# Generated by Django 5.1.4 on 2024-12-21 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0018_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAndAdminChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_list', models.JSONField(blank=True, null=True)),
                ('admin', models.OneToOneField(limit_choices_to={'role': 'super_administrator'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_student_chats', to=settings.AUTH_USER_MODEL)),
                ('student', models.OneToOneField(limit_choices_to={'role': 'student'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_admin_chats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'StudentAndTeacherChat',
                'verbose_name_plural': 'StudentAndTeacherChats',
            },
        ),
    ]
